<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>$(AssemblyPrefix).Client</AssemblyName>
    <TargetFrameworks>$(LibTargetFrameworks)</TargetFrameworks>
    <PackageId>$(PackagePrefix).Opc.Ua.Client.DPA</PackageId>
    <RootNamespace>Opc.Ua.Client</RootNamespace>
    <Description>Temporary OPC UA Client Class Library for dpa. Includes fix: https://github.com/OPCFoundation/UA-.NETStandard/pull/3707</Description>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Opc.Ua.Client.Tests" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageId>$(PackageId).Debug</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BitFaster.Caching" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Stack\Opc.Ua.Core\Opc.Ua.Core.csproj" />
    <ProjectReference Include="..\Opc.Ua.Configuration\Opc.Ua.Configuration.csproj" />
  </ItemGroup>
  <Target Name="GetPackagingOutputs" />
</Project>
